export default {
    types: {
        feat: { title: '🚀 Features' },
        fix: { title: '🐞 Bug Fixes' },
        perf: { title: '🏎 Performance' },
        chore: { title: '🏡 Chores' },
        refactor: { title: '🔨 Refactors' },
        revert: { title: '⏪ Revert' },
        docs: { title: '📝 Documentation' },
        style: { title: '🎨 Styles' },
        test: { title: '✅ Tests' },
        build: { title: '👷 Build System' },
        ci: { title: '🤖 Continuous Integration' },
        wip: { title: '🚧 Work in Progress' },
        release: { title: '📦 Release' },
        config: { title: '🔧 Config' },
        changelog: { title: '📝 Changelog' },
        merge: { title: '🍏 Merge' },
        mergeConflict: { title: '💬 Merge Conflict' },
        other: { title: '🤷 Other' },
    },
}
